=== rodrigoguzzo/teste2/integracaoSiscondj/src/main/resources/xsd/comarca-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="comarca.soap.integracaoSiscondj.tjrj.jus.br" 
	xmlns:tns="comarca.soap.integracaoSiscondj.tjrj.jus.br" elementFormDefault="qualified">
	
	<xs:element name="retornarTodasComarcasRequest">
		<xs:complexType>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="retornarTodasComarcasResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:integer" name="codigoRetorno"/>
        <xs:element name="listaComarcas" type="tns:Comarca" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Comarca">
  	<xs:sequence>
  		<xs:element name="codigo" type="xs:int"/>
		<xs:element name="instancia" type="xs:int"/>
		<xs:element name="nome" type="xs:string"/>
	</xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== rodrigoguzzo/teste2/integracaoSiscondj/files-xml/comarca-response.xml
<?xml version="1.0" encoding="UTF-8"?>
<retornarTodasComarcasResponse 
	xmlns="comarca.soap.integracaoSiscondj.tjrj.jus.br"
	xsi:schemaLocation="comarca.soap.integracaoSiscondj.tjrj.jus.br comarca-schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	
	<codigoRetorno>0</codigoRetorno>
	 <listaComarcas>
		 <codigo>5</codigo>
		 <instancia>1</instancia>
		 <nome>ALTO ALEGRE</nome>
	 </listaComarcas>
	 <listaComarcas>
		 <codigo>10</codigo>
		 <instancia>1</instancia>
		 <nome>BOA VISTA</nome>
	 </listaComarcas>
	 <listaComarcas>
		 <codigo>90</codigo>
		 <instancia>1</instancia>
		 <nome>BONFIM</nome>
	 </listaComarcas>
 </retornarTodasComarcasResponse>
