=== rodrigoguzzo/teste2/integracaoSiscondj/src/main/resources/xsd/processo-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="processo.soap.integracaoSiscondj.tjrj.jus.br" 
	xmlns:tns="processo.soap.integracaoSiscondj.tjrj.jus.br" elementFormDefault="qualified">
	
	<xs:element name="retornarProcessoPorNumeroRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="numeroProcesso" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="retornarProcessoPorNumeroResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:integer" name="codigoRetorno"/>
        <xs:element name="processos" type="tns:Processo"> </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Processo">
  	<xs:sequence>
		<xs:element name="codigoComarca" type="xs:int"/>
		<xs:element name="codigoServentia" type="xs:int"/>
		<xs:element name="instancia" type="xs:int"/>
		<xs:element name="numeroProcessoCNJ" type="xs:string" />
		<xs:element name="numeroProcessoTribunal" type="xs:string"/>
		<xs:element name="partes" type="tns:Parte" maxOccurs="unbounded" minOccurs="2" />
	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Parte">
  	<xs:sequence>
  		<xs:element name="cpfCnpj" type="xs:long"/>
		<xs:element name="nome" type="xs:string"/>
		<xs:element name="principal" type="xs:boolean"/>
		<xs:element type="xs:string" name="tipoParte"/>
		<xs:element type="xs:string" name="tipoPessoa"/>
	</xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== rodrigoguzzo/teste2/integracaoSiscondj/files-xml/processo-response.xml
<?xml version="1.0" encoding="UTF-8"?>
<retornarProcessoPorNumeroResponse 
	xmlns="processo.soap.integracaoSiscondj.tjrj.jus.br"
	xsi:schemaLocation="processo.soap.integracaoSiscondj.tjrj.jus.br processo-schema.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">	
<codigoRetorno>25</codigoRetorno> 
<processos> 
	<codigoComarca>10</codigoComarca>
	<codigoServentia>22</codigoServentia>
	<instancia>1</instancia>
	<numeroProcessoCNJ>0707245-83.2012.1.11.0010</numeroProcessoCNJ>
	<numeroProcessoTribunal>0707245-83.2012</numeroProcessoTribunal>
	<partes>
		<cpfCnpj>56838620197</cpfCnpj>
		<nome>Fulana de Tal</nome>
		<principal>true</principal>
		<tipoParte>AUTOR</tipoParte>
		<tipoPessoa>PESSOA_FISICA</tipoPessoa>
	</partes>	
	<partes>
		<cpfCnpj>12094725098191</cpfCnpj>
		<nome>Seguradora de Cons√≥rcios S/A</nome>
		<principal>true</principal>
		<tipoParte>REU</tipoParte>
		<tipoPessoa>PESSOA_JURIDICA</tipoPessoa>
	</partes>	
</processos>
</retornarProcessoPorNumeroResponse>
